version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./storage:/var/www/trantrace/storage/app/public/excel
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - "${DB_PORT}:3306"
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: php.dockerfile
    command: ["./wait_for_mysql.sh", "db", "${DB_PASSWORD}", "${DB_DATABASE}" ]
    restart: always
    container_name: trantrace
    ports:
      - "${WEB_PORT}:80"
    stdin_open: true
    tty: true
